services:
  - type: web
    name: mall-backend
    env: node
    buildCommand: "yarn install"
    startCommand: "node src/ server.js"
    envVars:
      - key: MONGO_URI
        value: ${mongodb.connectionString}
      - key: ADMIN_EMAIL
        value: "admin@mall.com"
      - key: ADMIN_PASSWORD
        value: "MallAdmin123"
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: true
    plan: free

databases:
  - name: mall-db
    databaseName: mall
